# 项目配置
project:
  # 名称
  name: demo
  # 版本
  version: 1.0.0

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# Spring配置
spring:
  profiles:
    active: @environment@
  # 热部署
  devtools:
    restart:
      # 重启开关
      enabled: true
  # 切面启用
  aop:
    proxy-target-class: true
    auto: true
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 发送邮件
  mail:
    host: smtp.163.com #发送方邮件服务器
    username: 15086680081@163.com #发送方邮箱地址
    password: lcs205455 #客户端授权码，不是邮箱密码
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

# 日志配置
logging:
  level:
    # 这里日志级别设为debug是为了打印SQL
    com.demo: debug
    org.springframework: warn
    # 避免找不到/templates而警告
    org.springframework.boot.autoconfigure.thymeleaf: error

# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.demo.business.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /shop/notice/*
  # 匹配链接（多个用逗号分隔）
  urlPatterns: /system/*,/monitor/*,/tool/*